
server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    password: root
    username: root
    url: jdbc:mysql//localhost:3306/fornecedor
  application:
    name: 'fornecedor'
  profiles:
    active: default
  cloud:
    config:
      uri: http:///localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka